name: Excercise
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # - name: Install nodejs
      #   uses: actions.setup-node@v3
      #   with:
      #     node-version: 18
      - name: Install dependency
        uses: npm ci
      - name: Run lint
        uses: npm run lint
      - name: Run test
        uses: npm run test
      - name: Run build
        uses: npm run build

      